services:
  yolox:
    build:
      context: .
      dockerfile: Dockerfile
    image: yolox-tpf:latest
    container_name: yolox
    shm_size: "8gb"
    stdin_open: true
    tty: true
    volumes:
      - ./YOLOX/datasets:/workspace/YOLOX/datasets
      - ./YOLOX/YOLOX_outputs:/workspace/YOLOX/YOLOX_outputs
      - ./weights:/workspace/YOLOX/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      python3 tools/train.py
      -f exps/example/custom/yolox_s_vehicles.py
      -d 1 -b 16 --fp16 -o
      -c weights/yolox_s.pth
