FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

# Instala apenas o essencial para OpenCV funcionar
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*

# Instala o ecossistema com o numpy travado
RUN pip install --no-cache-dir \
    "numpy<2.0.0" \
    torchvision==0.16.0 \
    transformers==4.40.0 \
    accelerate==0.29.0 \
    datasets \
    timm \
    pycocotools \
    opencv-python-headless \
    scikit-learn \
    pillow

COPY src/ /workspace/src/

CMD ["python", "src/train_detr.py"]