FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

ENV DEBIAN_FRONTEND=noninteractive
ENV PYHTONPATH=/workspace

RUN apt-get update && apt-get install -y git ffmeg libsm6 libxext6 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN pip install --no-cache-dir transformers datasets timm pycocotools opencv-python-headless scikit-learn

CMD [ "/bin/bash" ]