services:
  detr:
    build:
      context: .
      dockerfile: Dockerfile
    image: detr-tpf:latest
    container_name: detr
    shm_size: "8gb"
    stdin_open: true
    tty: true
    volumes:
      - ${DATASET_PATH}:/workspace/detr/coco
      - ./outputs:/workspace/detr/outputs
      - ./weights:/workspace/detr/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      python main.py
      --coco_path /workspace/detr/coco
      --output_dir /workspace/detr/outputs
      --resume weights/detr-r50_finetune.pth
      --batch_size 2
      --epochs 150
      --lr_drop 100
      --num_workers 4
      --early_stop_patience 20
