services:
  mrcnn:
    build:
      context: .
      dockerfile: Dockerfile
    image: maskrcnn-tpf:latest
    container_name: mrcnn
    shm_size: "8gb"
    stdin_open: true
    tty: true
    volumes:
      - "${DATASET_PATH}:/workspace/Dataset"
      - ./src:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python src/train_mrcnn.py
