services:
  mrcnn:
    build:
      context: .
      dockerfile: Dockerfile
    image: maskrcnn-tpf:latest
    container_name: mrcnn
    shm_size: "8gb"
    stdin_open: true
    tty: true
    environment:
      - DATASET_PATH=/workspace/Dataset
    volumes:
      - "${DATASET_PATH}:/workspace/Dataset:ro"
      - "./Mask_RCNN:/workspace/Mask_RCNN"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python samples/custom/custom.py train --weights=coco
