services:
  rcnn:
    build:
      context: .
      dockerfile: Dockerfile.rcnn
    volumes:
      # O Docker Compose vai buscar o valor de DATASET_PATH no arquivo .env
      - "${DATASET_PATH}:/workspace/Dataset"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]